include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gr.dart'

  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error